/**
 * Super-spec tests for specs/super-spec.json, generated by
 * scripts/build-super-spec.mjs (npm run spec:build).
 *
 * Covers: build determinism (byte-identical across runs, and the checked-in
 * artifact is current), per-service operation counts, exposure consistency
 * with catalog/manifest.json (ADR-0003: spec paths = manifest operations,
 * every one callable), the judicious skills representation (3 ops + embedded
 * index, NOT one path per skill/section), and the size budget the design doc
 * records (the compact form ships into the execute sandbox).
 */
import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { EXCLUDED_SCOUT_OPS } from "../scripts/exposure.mjs";
import { compactResponseSchema } from "../scripts/lib/super-spec-compaction.ts";
import { isOversizedOutputBlock } from "../src/catalog/output-compaction.ts";
import { lastIdSegment } from "../src/catalog/id.ts";
import {
  jsonSchemaToType,
  sanitizeToolName,
  toPascalCase,
  type JsonSchema
} from "../src/catalog/vendor/json-schema-types.ts";
import { resolveSpecRefs } from "../src/executor/spec-sandbox.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_PATH = join(ROOT, "specs", "super-spec.json");

type Operation = {
  operationId: string;
  summary?: string;
  description?: string;
  tags?: string[];
  requestBody?: { content?: Record<string, { schema?: Record<string, unknown> }> };
  responses?: Record<
    string,
    {
      description?: string;
      content?: Record<string, { schema?: Record<string, unknown> }>;
    }
  >;
  "x-service": string;
  "x-execute"?: string;
  "x-algolia"?: unknown;
  "x-skill-index"?: Array<{ id: string; source: string; description: string; sections: string[] }>;
  "x-runnable-index"?: Array<{
    id: string;
    description: string;
    inputSchema: Record<string, unknown>;
    outputSchema: Record<string, unknown>;
  }>;
};

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as {
  openapi: string;
  info: Record<string, unknown>;
  paths: Record<string, Record<string, Operation>>;
  components: Record<string, Record<string, unknown>>;
  "x-services": Record<string, unknown>;
};

const manifest = JSON.parse(readFileSync(join(ROOT, "catalog", "manifest.json"), "utf8")) as {
  entries: Array<{
    id: string;
    service: string;
    kind: string;
    description: string;
    runnable?: true;
    inputSchema: Record<string, unknown> | null;
    outputSchema: Record<string, unknown> | null;
  }>;
};

function allOps(): Array<[string, string, Operation]> {
  const out: Array<[string, string, Operation]> = [];
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) out.push([path, method, op]);
  }
  return out;
}

function operationById(
  document: typeof spec,
  id: string
): Operation {
  const match = Object.values(document.paths)
    .flatMap((item) => Object.values(item))
    .find((op) => op.operationId === id);
  if (!match) throw new Error(`missing operation ${id}`);
  return match;
}

function outputBlock(entry: (typeof manifest.entries)[number]): string | undefined {
  if (!entry.outputSchema) return undefined;
  const typeBase = toPascalCase(sanitizeToolName(lastIdSegment(entry.id)));
  return jsonSchemaToType(entry.outputSchema as JsonSchema, `${typeBase}Output`);
}

describe("build determinism", () => {
  it("the checked-in artifact is current, and two rebuilds are byte-identical", () => {
    const before = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const first = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const second = readFileSync(SPEC_PATH);
    expect(Buffer.compare(first, second)).toBe(0);
    expect(
      Buffer.compare(before, first),
      "specs/super-spec.json is stale — run npm run spec:build"
    ).toBe(0);
  });
});

describe("shape and counts", () => {
  it("is an OpenAPI-3.1-style doc with the four service tags", () => {
    expect(spec.openapi).toBe("3.1.0");
    expect(Object.keys(spec["x-services"]).sort()).toEqual([
      "lumenloop",
      "scout",
      "skills",
      "stellarDocs"
    ]);
  });

  it("has the expected per-service operation counts (exposed ops only, ADR-0003)", () => {
    const counts: Record<string, number> = {};
    for (const [, , op] of allOps()) {
      counts[op["x-service"]] = (counts[op["x-service"]] ?? 0) + 1;
    }
    // Exactly the manifest operations: excluded ops (paid research, account
    // surface, scout writes) never reach the spec.
    expect(counts.lumenloop).toBe(18);
    expect(counts.scout).toBe(30);
    expect(counts.stellarDocs).toBe(12);
    expect(counts.skills).toBe(4); // list, read, ranked search, run_skill (design §5)
  });

  it("every path is '/{service}/{operation}' and operationIds are unique callable ids", () => {
    const seen = new Set<string>();
    for (const [path, , op] of allOps()) {
      expect(path.startsWith(`/${op["x-service"]}/`), path).toBe(true);
      expect(seen.has(op.operationId), `duplicate ${op.operationId}`).toBe(false);
      seen.add(op.operationId);
      expect(op.tags?.[0]).toBe(op["x-service"]);
    }
  });

  it("every op carries an exact x-execute call line (everything in the spec is callable)", () => {
    for (const [, , op] of allOps()) {
      expect(op["x-execute"], op.operationId).toBeTruthy();
    }
    // Service ops are called as `await <operationId>(args)`.
    for (const [, , op] of allOps()) {
      if (op["x-service"] !== "skills") {
        expect(op["x-execute"]).toBe(`await ${op.operationId}(args)`);
      }
    }
  });

  it("describes search scores on the shared cross-tier interleave scale", () => {
    const search = spec.paths["/skills/search_skills"]!.post!;
    const description = search.responses?.["200"]?.description ?? "";
    expect(description).toContain("Scores share one scale");
    expect(description).toContain(">=1.6x");
    expect(description).toContain("hit order is authoritative");
    expect(description).toContain("absolute top-two score gap");
    expect(description).toContain("recoveryMetadata");
    expect(description).not.toMatch(/always ranked below every gated hit/i);
    expect(description).not.toMatch(/only among same-tier/i);
    expect(search.summary).toBe("Ranked lexical search over whole skills.");
    expect(search.description).toContain("sections remain readable");
    expect(search.description).toContain("not independent ranked hits");
    expect(search["x-execute"]).toBe(
      'await codemode.search({ query, kind: "skill", service: "skills" })'
    );
  });
});

describe("consistency with the catalog (single source of truth)", () => {
  it("every cataloged operation id appears as an operationId (spec = manifest)", () => {
    const byOperationId = new Map(allOps().map(([, , op]) => [op.operationId, op]));
    const catalogOps = manifest.entries.filter((e) => e.kind === "operation");
    expect(catalogOps.length).toBe(18 + 30 + 12);
    for (const entry of catalogOps) {
      expect(
        byOperationId.get(entry.id),
        `catalog op ${entry.id} missing from super spec`
      ).toBeDefined();
    }
    // …and the reverse: no service op in the spec lacks a manifest entry.
    const manifestIds = new Set(catalogOps.map((e) => e.id));
    for (const [, , op] of allOps()) {
      if (op["x-service"] === "skills") continue; // synthetic core service
      expect(manifestIds.has(op.operationId), `spec-only op ${op.operationId}`).toBe(true);
    }
  });

  it("leaks no excluded endpoint and leaves no dangling component ref (ADR-0003)", () => {
    // The spec is serialized into the sandbox and returned by codemode.spec(),
    // so it is emitted text. Components are copied wholesale from upstream, so
    // a schema describing only an EXCLUDED operation rode along and carried
    // that endpoint's prose with it: scout.FeedbackRequest — the request body
    // of the excluded POST /api/feedback — shipped the raw path this way.
    // build-super-spec.mjs now prunes unreachable components and guards the
    // emitted text.
    // Derived from the exclusion data, never a hand-copied list — a fourth
    // exclusion must tighten this test automatically (house rule, same as
    // test/demo-page.test.ts).
    const serialized = JSON.stringify(spec);
    const excludedPaths = [...EXCLUDED_SCOUT_OPS].map((op) => op.split(" ")[1]!);
    expect(excludedPaths.length).toBeGreaterThan(0);
    for (const path of excludedPaths) {
      expect(serialized.includes(path), `super-spec emits excluded endpoint ${path}`).toBe(false);
    }
    const components = (spec as unknown as { components?: Record<string, Record<string, unknown>> })
      .components ?? {};
    expect(components.schemas?.["scout.FeedbackRequest"]).toBeUndefined();

    // The dangerous direction is the OPPOSITE of the leak: pruning too much.
    // A dropped-but-still-referenced component resolves to `undefined` at
    // runtime (src/executor/spec-sandbox.ts) and vanishes on serialization, so
    // the model would silently receive a degraded contract instead of an error.
    // Verify by RESOLUTION, deliberately not by re-running the build's own
    // reachability walk — a copy of that walk would share any bug it has.
    const dangling: string[] = [];
    const walk = (node: unknown, path: string): void => {
      if (!node || typeof node !== "object") return;
      if (Array.isArray(node)) {
        node.forEach((item, i) => walk(item, `${path}/${i}`));
        return;
      }
      for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
        if (typeof value === "string") {
          const match = value.match(/^#\/components\/([^/]+)\/([^/]+)/);
          if (match) {
            const group = match[1]!;
            const name = match[2]!.replace(/~1/g, "/").replace(/~0/g, "~");
            if (!components[group]?.[name]) dangling.push(`${path}/${key} -> ${value}`);
          }
        } else {
          walk(value, `${path}/${key}`);
        }
      }
    };
    walk(spec, "");
    expect(dangling, "component refs that no longer resolve — the build pruned something live").toEqual([]);
  });

  it("the skills index matches the catalog's exposed (allowed) skills and its section slugs resolve", () => {
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    // Exposure-aware: the index advertises exactly the cataloged skills — the
    // 7 retired Lumenloop onboarding skills have no manifest entry (ADR-0003)
    // and must not appear here.
    const catalogSkillIds = manifest.entries
      .filter((e) => e.service === "skills" && e.kind === "skill")
      .map((e) => e.id)
      .sort();
    expect(index.map((s) => s.id)).toEqual(catalogSkillIds);

    // Heading-list-only index: every listed section corresponds to a cataloged
    // skill-section entry (file:… keys verbatim; headings via the shared slug).
    const sectionIds = new Set(
      manifest.entries.filter((e) => e.kind === "skill-section").map((e) => e.id)
    );
    const slugify = (text: string) =>
      text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "") || "section";
    let checked = 0;
    for (const skill of index) {
      const used = new Set<string>();
      for (const section of skill.sections) {
        let key: string;
        if (section.startsWith("file:")) {
          key = section;
        } else {
          let slug = slugify(section);
          for (let n = 2; used.has(slug); n++) slug = `${slugify(section)}-${n}`;
          used.add(slug);
          key = slug;
        }
        expect(sectionIds.has(`${skill.id}#${key}`), `${skill.id}#${key}`).toBe(true);
        checked += 1;
      }
    }
    expect(checked).toBe(sectionIds.size); // every cataloged section is discoverable in the index
  });

  it("read_skill's name enum is exactly the exposed skill ids", () => {
    const schema = spec.paths["/skills/read_skill"]!.post!.requestBody!.content![
      "application/json"
    ]!.schema as { properties: { name: { enum: string[] } } };
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    expect(schema.properties.name.enum).toEqual(index.map((s) => s.id));
  });
});

describe("oversized response-schema compaction", () => {
  it("preserves required names that have no matching property", () => {
    const fixture = JSON.parse(
      readFileSync(
        join(ROOT, "test", "fixtures", "super-spec", "required-without-property.json"),
        "utf8"
      )
    ) as {
      id: string;
      outputSchema: Record<string, unknown>;
    };
    const compact = compactResponseSchema(fixture);

    expect(compact.properties).toEqual({ present: {} });
    expect(compact.required).toEqual(["present", "missing"]);
    expect(compact.type).toBe("object");
    expect(compact["x-codemode-describe"]).toBe(
      'codemode.describe("fixture.requiredWithoutProperty")'
    );
  });

  it("compacts exactly the operation outputs selected by the shared threshold", () => {
    const catalogOps = manifest.entries.filter((entry) => entry.kind === "operation");
    const expected = catalogOps
      .filter((entry) => {
        const block = outputBlock(entry);
        return block !== undefined && isOversizedOutputBlock(block);
      })
      .map((entry) => entry.id)
      .sort();
    const actual = allOps()
      .filter(([, , op]) => {
        const schema = op.responses?.["200"]?.content?.["application/json"]?.schema;
        return schema?.["x-codemode-describe"] !== undefined;
      })
      .map(([, , op]) => op.operationId)
      .sort();

    expect(actual).toEqual(expected);
    expect(actual.length).toBeGreaterThan(0);
  });

  it("keeps exact top-level field names and an exact-id describe pointer", () => {
    for (const entry of manifest.entries.filter((candidate) => candidate.kind === "operation")) {
      const block = outputBlock(entry);
      if (block === undefined || !isOversizedOutputBlock(block)) continue;

      const schema = operationById(spec, entry.id).responses?.["200"]?.content?.[
        "application/json"
      ]?.schema as Record<string, unknown>;
      const expectedKeys = Object.keys(entry.outputSchema?.properties ?? {}).sort();
      const properties = schema.properties as Record<string, unknown> | undefined;
      expect(Object.keys(properties ?? {}).sort(), entry.id).toEqual(expectedKeys);
      expect(schema.required, entry.id).toEqual(entry.outputSchema?.required);
      expect(schema.type, entry.id).toEqual(entry.outputSchema?.type);
      expect(schema["x-codemode-describe"], entry.id).toBe(
        `codemode.describe(${JSON.stringify(entry.id)})`
      );
      expect(schema.description, entry.id).toContain(
        `codemode.describe(${JSON.stringify(entry.id)})`
      );
      expect(JSON.stringify(schema).length, entry.id).toBeLessThan(
        JSON.stringify(entry.outputSchema).length
      );
    }
  });

  it("keeps every non-oversized output schema equivalent after ref resolution", () => {
    const resolved = resolveSpecRefs(spec) as typeof spec;
    let checked = 0;
    for (const entry of manifest.entries.filter((candidate) => candidate.kind === "operation")) {
      const block = outputBlock(entry);
      if (block === undefined || isOversizedOutputBlock(block)) continue;

      const schema = operationById(resolved, entry.id).responses?.["200"]?.content?.[
        "application/json"
      ]?.schema;
      expect(schema, entry.id).toEqual(entry.outputSchema);
      checked += 1;
    }
    expect(checked).toBeGreaterThan(0);
  });
});

describe("runnable skills — /skills/run_skill (design §5)", () => {
  const runSkillOp = () => spec.paths["/skills/run_skill"]!.post!;

  it("exists with the exact dispatch line under the skills service", () => {
    const op = runSkillOp();
    expect(op).toBeDefined();
    expect(op.operationId).toBe("skills.run_skill");
    expect(op["x-service"]).toBe("skills");
    expect(op["x-execute"]).toBe("await codemode.skill.run(name, input)");
  });

  it("name enum is exactly the manifest's runnable skill ids, in manifest (id-sorted) order", () => {
    const schema = runSkillOp().requestBody!.content!["application/json"]!.schema as {
      additionalProperties: boolean;
      required: string[];
      properties: { name: { enum: string[] } };
    };
    const runnableIds = manifest.entries.filter((e) => e.runnable === true).map((e) => e.id);
    expect(runnableIds.length).toBeGreaterThan(0);
    expect(schema.properties.name.enum).toEqual(runnableIds);
    expect(schema.required).toEqual(["name", "input"]);
    expect(schema.additionalProperties).toBe(false);
  });

  it("x-runnable-index matches the manifest entries byte-for-byte (id, description, both schemas)", () => {
    const index = runSkillOp()["x-runnable-index"]!;
    const runnable = manifest.entries.filter((e) => e.runnable === true);
    expect(index.map((s) => s.id)).toEqual(runnable.map((e) => e.id));
    for (const item of index) {
      const entry = runnable.find((e) => e.id === item.id)!;
      expect(item.description).toBe(entry.description);
      // Both artifacts are sortKeysDeep'd by their builders, so JSON string
      // equality is byte equality — the assertRunnersWired pinning, checked
      // across the two emitted surfaces.
      expect(JSON.stringify(item.inputSchema), item.id).toBe(JSON.stringify(entry.inputSchema));
      expect(JSON.stringify(item.outputSchema), item.id).toBe(JSON.stringify(entry.outputSchema));
    }
  });
});

describe("service specifics", () => {
  it("stellarDocs ops keep the algolia mapping as a vendor extension", () => {
    const docsOps = allOps().filter(([, , op]) => op["x-service"] === "stellarDocs");
    for (const [, , op] of docsOps) {
      expect(op["x-algolia"], op.operationId).toBeDefined();
    }
    const backend = (spec["x-services"].stellarDocs as { backend: { type: string } }).backend;
    expect(backend.type).toBe("algolia");
  });

  it("carries the authored Docs page-sections output schema", () => {
    const op = spec.paths["/stellarDocs/get_doc_page_sections"]!.post!;
    const schema = op.responses!["200"]!.content!["application/json"]!.schema as {
      required: string[];
      properties: {
        sections: { items: { required: string[]; properties: Record<string, unknown> } };
      };
    };
    expect(schema.required).toEqual(["page", "sections", "nbSections", "complete", "truncated"]);
    expect(schema.properties.sections.items.required).not.toContain("content");
    expect(schema.properties.sections.items.properties).toHaveProperty("content");
    expect(schema.properties.sections.items.properties).toHaveProperty("snippet");
  });

  it("carries the current scout.getRfps contract", () => {
    const op = spec.paths["/scout/getRfps"]!.get!;
    expect(op.description).toContain("the sponsor brief is still soliciting");
    expect(op.description).toContain("meta.scfRound.submissionWindow");
    expect(op.description).not.toContain("open briefs are fundable in the current SCF round");
    const status = (op as Operation & { parameters: Array<{ name: string; description: string }> })
      .parameters.find((parameter) => parameter.name === "status")!;
    expect(status.description).toContain("brief is still soliciting");
    expect(status.description).toContain("submissionWindow");
    expect(status.description).toContain("currentPhase");
    const entry = manifest.entries.find((candidate) => candidate.id === "scout.getRfps")!;
    const schema = entry.outputSchema as {
      properties: {
        meta: { properties: { scfRound: { properties: Record<string, unknown> } } };
        rfps: { items: { properties: Record<string, { description?: string }> } };
      };
    };
    const round = schema.properties.meta.properties.scfRound.properties;
    expect(round).toHaveProperty("currentPhase");
    expect(round).toHaveProperty("roundsInProgress");
    expect(round).toHaveProperty("verifyAt");
    expect(schema.properties.rfps.items.properties.status!.description).toContain(
      "brief is still soliciting"
    );
  });

  it("scout $refs resolve within the merged doc (namespaced components)", () => {
    const refs = JSON.stringify(spec.paths).match(/"\$ref":"([^"]+)"/g) ?? [];
    expect(refs.length).toBeGreaterThan(0);
    for (const raw of refs) {
      const ref = raw.slice('"$ref":"'.length, -1);
      expect(ref.startsWith("#/components/"), ref).toBe(true);
      const [, , group, name] = ref.split("/");
      expect(
        (spec.components[group!] as Record<string, unknown>)[name!],
        `unresolvable ${ref}`
      ).toBeDefined();
    }
  });

  it("lumenloop tool descriptions carry when_to_use/returns; excluded ops have no path", () => {
    const searchDirectory = spec.paths["/lumenloop/search_directory"]!.post!;
    expect(searchDirectory.description).toContain("When to use:");
    expect(searchDirectory.description).toContain("Returns:");
    // The paid research trigger and the account surface are build-time
    // excluded (ADR-0003) — they do not exist in the spec at all.
    expect(spec.paths["/lumenloop/request_research"]).toBeUndefined();
    expect(JSON.stringify(Object.keys(spec.paths))).not.toContain("webhook");
  });

  it("matches the corrected Lumenloop prose and Scout inputs in the model spec", () => {
    const entity = spec.paths["/lumenloop/find_content_by_entity"]!.post!;
    const related = spec.paths["/lumenloop/get_related_projects"]!.post!;
    const av = spec.paths["/lumenloop/find_av_passages"]!.post!;
    const hackathon = spec.paths["/scout/searchHackathonBuilds"]!.get!;

    expect(entity.responses?.["200"]?.description).toContain("Content grouped by type in articles");
    expect(related.responses?.["200"]?.description).toContain("An object with content");
    const avOperationDescription = av.description?.split("\n\n")[0];
    expect(avOperationDescription).toBe(
      "Find specific passages in long videos, podcasts, and recorded talks by semantic similarity. Returns parent recording metadata, AI summaries, and an opaque ordering offset."
    );
    expect(avOperationDescription).not.toContain("Transcript text");
    expect(av.responses?.["200"]?.description).toContain(
      "created_at (upstream metadata; do not treat it as the recording date or recency evidence)"
    );
    expect(av.description).not.toContain("matched chunk text");
    expect(av.description).not.toContain("recording's date");
    expect(av.description).not.toContain("quote what was said");
    expect((hackathon as { parameters?: Array<{ name: string }> }).parameters?.map((p) => p.name).sort()).toEqual([
      "limit",
      "q",
      "track",
      "winnersOnly"
    ]);
  });
});

describe("size budget (design doc §4)", () => {
  it("the compact form that ships into the execute sandbox stays under 300 KiB", () => {
    const compact = Buffer.byteLength(JSON.stringify(spec), "utf8");
    expect(compact).toBeLessThan(300 * 1024);
  });
});
